version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9050:9050"
    volumes:
      - .:/app

  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "6080:80"
    depends_on:
      - backend
